apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  # Type LoadBalancer exposes the service externally. In Kind, this maps
  # to the host port we configured in Terraform.
  type: LoadBalancer 
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80 # The port the service is available on
    targetPort: 5000 # The port the container is listening on